---
---
---

```{=html}
<style>
  body{
  font-family: Helvetica;
  font-size: 12pt;
  line-height:2em;
}
</style>
```
## CASA0005 GIS homework 4

#### Step 1 load the data

first of all, load all the relevant packages.

```{r 1.1 Load the packages, eval=FALSE}
library(sf)
library(here)
library(janitor)
library(tidyverse)
```

load the shp file of `spatial data of the World` from <https://hub.arcgis.com/datasets/2b93b06dc0dc4e809d3c8db5cb96ba69_0/explore?location=-2.688200%2C0.000000%2C1.41>

load the csv file of `global gender inequality data` from <http://hdr.undp.org/en/indicators/68606#>

```{r 1.2 Load the data, eval=FALSE}
countries <- st_read(here("Data", "World_Countries__Generalized_.shp"))

gii_csv <- read_csv(here("Data",'Gender Inequality Index.csv'),locale = locale(encoding = "latin1"),skip=5,na = "..")

```

#### Step 2 process the data

```{r 2.1 calculate inequality difference, echo=TRUE}
gii_diff <- gii_csv %>%
  clean_names() %>%
  slice(1:189) %>%
  select(contains('country'),contains('2010'),contains('2019')) %>%
  mutate(inequality_difference = x2019-x2010)

head(gii_diff,10)
```

```{r 2.1 using country package to produce a iso_code, echo=TRUE}

library(countrycode)

gii_diff_iso <- gii_diff %>% 
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))
```

After generating all of those difference, we can now join those attributes to the shapefile.

```{r 2.3 Join datas, echo=TRUE}
countries_gii <- countries %>%
  clean_names() %>%
  left_join(., 
            gii_diff_iso,
            by = c("aff_iso" = "iso_code"))

head(countries_gii,10)
```
